# A collection of requests to test the REST API (to use with Visual Studio Code Rest Client extension)

# Variables
@host = http://localhost:5000/api
@json = Content-Type: application/json
# @auth = Authorization: Basic joe@smith.com joepassword
@auth = Authorization: Basic Sally@jones.com sallypassword

# get info for authenticated user
GET {{host}}/users HTTP/1.1
{{auth}}

###

# create new user

POST {{host}}/users HTTP/1.1
{{json}}

{
  "firstName": "Lara",
  "lastName": "Croft",
  "emailAddress": "lara@croftmanor.co.uk",
  "password": "jaffacakes214"
}

###

POST {{host}}/users HTTP/1.1
{{json}}

{
  "firstName": "Kenneth",
  "lastName": "Schultz",
  "emailAddress": "Bernie.Brakus62@gmail.com",
  "password": "0fmOUO6BeRAMQy8"
}

###

# get all courses
GET {{host}}/courses HTTP/1.1

###

# get a specific course
GET {{host}}/courses/8 HTTP/1.1

###

# get a specific course (random)
GET {{host}}/courses/{{$randomInt 1 8}} HTTP/1.1

###


# add a new course
POST {{host}}/courses HTTP/1.1
{{auth}}
{{json}}

{
  "title": "Quantifying Primary Alarm",
  "description": "Sed enim omnis qui modi consequuntur. Sed inventore et impedit ea voluptas quasi eum assumenda sit. Modi neque odit provident reprehenderit et. Nam et occaecati aut vitae.",
  "estimatedTime": "4 hours",
  "materialsNeeded": "Fantastic Metal",
  "userId": "5"
}

###

# update a course
PUT {{host}}/courses/7 HTTP/1.1
{{auth}}
{{json}}

{
  "title": "Copying Neural Driver",
  "description": "Voluptate modi aut. Ex consequatur sequi voluptatem dolor. Mollitia facere laudantium minima consequatur ratione alias animi.",
  "estimatedTime": "13 hours",
  "materialsNeeded": "Old Granite",
  "userId": "8"
}

###

# delete a course
DELETE {{host}}/courses/6 HTTP/1.1
{{auth}}
{{json}}
